services:
  accounting.api:
    image: ${DOCKER_REGISTRY-}accountingapi
    build:
      context: .
      dockerfile: Accounting.API/Dockerfile
    networks:
      - agentic-network   

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Inventory.API/Dockerfile
    networks:
      - agentic-network

  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    command: ["dotnet", "ClientApp.dll", "--interactive"]
    depends_on:
      - ollama
    networks:
      - agentic-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - agentic-network

volumes:
  ollama:

networks:
  agentic-network:
    external: true
